spring.application.name=shopapp_backend
server.address=0.0.0.0
server.port=3000

spring.datasource.url=jdbc:postgresql://localhost:5432/shopapp
spring.datasource.username=postgres
spring.datasource.password=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# GOOGLE

spring.security.oauth2.client.registration.google.client-id=803658319002-54q9s6jqnh5hatlm00b002180n3t80j3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

# FACEBOOK

spring.security.oauth2.client.registration.facebook.client-id=853720010568020
spring.security.oauth2.client.registration.facebook.client-secret=c042b73f5da809e7652ef463db2847b6

# JWT
jwt.secret=shopapp_super_secret_key_2026_hua_khanh_duy_very_secure_secret
jwt.expiration=86400000

# MULTIPART UPLOADS
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# MAIL CONFIGURATION
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:your-email@gmail.com}
spring.mail.password=${MAIL_PASSWORD:your-app-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# RESET PASSWORD URL
app.reset-password-url=https://gleeful-mummy-polka.ngrok-free.dev/#/reset-password